### ISSUE TITLE
你好，开发FIDO时遇到了一个问题，麻烦帮下忙

### ISSUE THREAD

**Issue by MaosanDao** [SickWorm/FIDO-UAF-Chinese-Document#1]
错误提示如下：

2019-11-21 09:48:08.889 19591-19609/? E/FIDO: com.fido.uaf.ver0100.types.UafException: UNTRUSTED_FACET_ID (Failed to retrieve facetID)
        at com.noknok.android.uaf.framework.service.FacetIDsValidator.validateCaller(FacetIDsValidator.java:190)
        at com.noknok.android.uaf.framework.service.UafProcessor.processUafRequest(UafProcessor.java:74)
        at com.noknok.android.uaf.framework.service.UafIntentProcessor.processIntent(UafIntentProcessor.java:130)
        at com.noknok.android.uaf.framework.service.MfacIntentActivity$UafProcessorTask.doInBackground(MfacIntentActivity.java:77)
        at com.noknok.android.uaf.framework.service.MfacIntentActivity$UafProcessorTask.doInBackground(MfacIntentActivity.java:64)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

部分FIDO部分的提示为：

2019-11-21 10:03:20.186 19591-20148/? I/FIDO: Need to update TrustedFacets list
2019-11-21 10:03:20.186 19591-20148/? I/FIDO: Send request to https://blog.make3.cn/fidouaf/v1/public/uaf/facets

我去注册的时候，提示以上的log，但是查阅不到相关的资料，不知道该如何解决，切入点也没有，希望能给与点帮助 谢谢！

**Comment by MaosanDao** [comment]
为什么会提示检索不到facetid，但是这个接口明明有啊·

**Comment by MaosanDao** [comment]
> 为什么会提示检索不到facetid，但是这个接口明明有啊·

不受信任的facetID，请问该如何让fido识别为可信任的facetID？求解

**Comment by sickworm** [comment]
不太清楚你请求的服务器是哪台，正常流程需要提交 app 的 meta data给 fido server 的管理员，服务器登记了你的 facetID 后才可以访问

**Comment by MaosanDao** [comment]
> 不太清楚你请求的服务器是哪台，正常流程需要提交 app 的 meta data给 fido server 的管理员，服务器登记了你的 facetID 后才可以访问

你好 确实因为是这个问题。我加入的我facetid后便可以通过了，不过有出现另外一个问题。我怀疑是没有将我的aaid加入到被信任的列表中了，不知道是否是我想的这样：

日志如下：

2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:1
2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:0
2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:"android:apk-key-hash:QM1hAKXXm9uxhxw1m9vRTxpXNEo"
2019-11-21 11:37:31.064 25155-25283/? I/chatty: uid=10108(com.huawei.fido.uafclient) AsyncTask #2 identical 1 line
2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:"android:apk-key-hash:QM1hAKXXm9uxhxw1m9vRTxpXNEo"
2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:"android:apk-key-hash:gZ4Vkgb6Sd7MtSHOGRQbwu6KdWI"
2019-11-21 11:37:31.064 25155-25283/? D/RestrictGson: deserialize:"android:apk-key-hash:QM1hAKXXm9uxhxw1m9vRTxpXNEo"
2019-11-21 11:37:31.064 25155-25283/? I/FIDO: Accepted.
2019-11-21 11:37:31.065 25155-25283/? I/FIDO_CLIENT: config file path = /system/emui/base/fido/hwfidoconfig.json
2019-11-21 11:37:31.066 25155-25283/? W/FIDO_CLIENT: not in [blackList]: pkgName:org.lyreg.fido_uaf_android_demo apkHash:android:apk-key-hash:gZ4Vkgb6Sd7MtSHOGRQbwu6KdWI
2019-11-21 11:37:31.067 25155-25283/? E/UAFLocalASMCommunicationClient: java.lang.ClassNotFoundException: com.noknok.android.client.asm.core.uaf.LocalAsmAgent
2019-11-21 11:37:31.068 25155-25283/? E/.fido.uafclien: Invalid ID 0x00000000.
2019-11-21 11:37:31.070 25155-25283/? I/FIDO: NO_SUITABLE_AUTHENTICATOR
2019-11-21 11:37:31.070 25155-25283/? E/FIDO: com.fido.uaf.ver0100.types.UafException: NO_SUITABLE_AUTHENTICATOR
        at com.noknok.android.uaf.framework.service.UafProcessor.processRegister(UafProcessor.java:260)
        at com.noknok.android.uaf.framework.service.UafProcessor.processUafRequest(UafProcessor.java:109)
        at com.noknok.android.uaf.framework.service.UafIntentProcessor.processIntent(UafIntentProcessor.java:130)
        at com.noknok.android.uaf.framework.service.MfacIntentActivity$UafProcessorTask.doInBackground(MfacIntentActivity.java:77)
        at com.noknok.android.uaf.framework.service.MfacIntentActivity$UafProcessorTask.doInBackground(MfacIntentActivity.java:64)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

**Comment by sickworm** [comment]
是的，需要添加。可以看看服务器返回的 Policy 有没有你的 aaid

**Comment by MaosanDao** [comment]
好的 非常感谢，正在尝试中

**Comment by MaosanDao** [comment]
> 是的，需要添加。可以看看服务器返回的 Policy 有没有你的 aaid

已经跑通了，再次表示由衷的感谢！
